apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: shei99/backstage-testing
spec:
  type: other
  lifecycle: unknown
  owner: guests
  dependsOn:
    - environmentVariables:default/backstage-testing-env
---
apiVersion: example.com/v1
kind: EnvironmentVariables
metadata:
  name: backstage-testing-env
spec:
  environmentVariables:
    - name: foo
      description: this is used to do foo
      version: 3.3.0
    - name: foobar
      description: this is used to do foobar
      version: 3.4.0
    - name: bar
      description: this is used to do bar
      version: 3.4.0
    - name: test
      description: this is used to do test
      version: 3.5.0
