apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: shei99/backstage-testing
spec:
  type: other
  lifecycle: unknown
  owner: guests
  relations:
    - type: example.com/v1/EnvironmentVariables
      target: backstage-testing-env
---
apiVersion: example.com/v1
kind: EnvironmentVariables
metadata:
  name: backstage-testing-env
spec:
  environmentVariables:
    - name: foobar
      description: this is used to do x
      version: 3.3.0
